[package]
name = "data_backup_and_recovery"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sha2 = "0.9.8"
chrono = "0.4"
fastrand = "1.3.4"
rand = "0.5.4"
borsh = "0.9.1"